"""Added category and priority fields to Task model

Revision ID: 416bb8bf2fcd
Revises: 
Create Date: 2024-12-16 03:42:20.763157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '416bb8bf2fcd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('due_date',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('due_date',
               existing_type=sa.String(length=50),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
