"""Add comments field to tasks

Revision ID: 5fef7707dbee
Revises: 416bb8bf2fcd
Create Date: 2024-12-18 02:40:31.427593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fef7707dbee'
down_revision = '416bb8bf2fcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('comments')

    # ### end Alembic commands ###
